"""Add threshold field to Ingredient model

Revision ID: 17d79ca40a54
Revises:
Create Date: 2025-11-14 06:34:43.838703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d79ca40a54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dish_name'), ['name'], unique=True)

    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_ingredient_quantity'), ['quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_threshold'), ['threshold'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingredient_unit'), ['unit'], unique=False)

    op.create_table('dish_ingredients',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'ingredient_id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    op.drop_table('dish_ingredients')
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_unit'))
        batch_op.drop_index(batch_op.f('ix_ingredient_threshold'))
        batch_op.drop_index(batch_op.f('ix_ingredient_quantity'))
        batch_op.drop_index(batch_op.f('ix_ingredient_name'))

    op.drop_table('ingredient')
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dish_name'))

    op.drop_table('dish')
    # ### end Alembic commands ###
