"""Add threshold column to Ingredients

Revision ID: ff9dd90048d2
Revises: cb3f0eb8084c
Create Date: 2025-11-14 19:50:04.994087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9dd90048d2'
down_revision = 'cb3f0eb8084c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ingredient_threshold'), ['threshold'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_threshold'))
        batch_op.drop_column('threshold')

    # ### end Alembic commands ###
